version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sukoon-db
    environment:
      POSTGRES_DB: sukoon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rare@rabbit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring-boot
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: